run.config:
  # wordlists location should be in resource folder
  wordlists: wordlist1.txt, wordlist2.txt
  # configurable status codes which should be treated as successful
  codes: 200, 301
  stop:
    # status codes that should stop processing after number of retries
    codes: 500, 501, 502, 503, 504, 505
    # number of retries for stop status codes
    retries: 3
  # number of threads used for testing
  threads: 10

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: toor
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false